/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BoardRouteImport } from './routes/board'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BoardIndexRouteImport } from './routes/board.index'
import { Route as BoardAllRouteImport } from './routes/board.all'
import { Route as BoardFolderRouteImport } from './routes/board.$folder'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardRoute = BoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardIndexRoute = BoardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BoardRoute,
} as any)
const BoardAllRoute = BoardAllRouteImport.update({
  id: '/all',
  path: '/all',
  getParentRoute: () => BoardRoute,
} as any)
const BoardFolderRoute = BoardFolderRouteImport.update({
  id: '/$folder',
  path: '/$folder',
  getParentRoute: () => BoardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/board': typeof BoardRouteWithChildren
  '/login': typeof LoginRoute
  '/board/$folder': typeof BoardFolderRoute
  '/board/all': typeof BoardAllRoute
  '/board/': typeof BoardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/board/$folder': typeof BoardFolderRoute
  '/board/all': typeof BoardAllRoute
  '/board': typeof BoardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/board': typeof BoardRouteWithChildren
  '/login': typeof LoginRoute
  '/board/$folder': typeof BoardFolderRoute
  '/board/all': typeof BoardAllRoute
  '/board/': typeof BoardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/board'
    | '/login'
    | '/board/$folder'
    | '/board/all'
    | '/board/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/board/$folder' | '/board/all' | '/board'
  id:
    | '__root__'
    | '/'
    | '/board'
    | '/login'
    | '/board/$folder'
    | '/board/all'
    | '/board/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoardRoute: typeof BoardRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board': {
      id: '/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board/': {
      id: '/board/'
      path: '/'
      fullPath: '/board/'
      preLoaderRoute: typeof BoardIndexRouteImport
      parentRoute: typeof BoardRoute
    }
    '/board/all': {
      id: '/board/all'
      path: '/all'
      fullPath: '/board/all'
      preLoaderRoute: typeof BoardAllRouteImport
      parentRoute: typeof BoardRoute
    }
    '/board/$folder': {
      id: '/board/$folder'
      path: '/$folder'
      fullPath: '/board/$folder'
      preLoaderRoute: typeof BoardFolderRouteImport
      parentRoute: typeof BoardRoute
    }
  }
}

interface BoardRouteChildren {
  BoardFolderRoute: typeof BoardFolderRoute
  BoardAllRoute: typeof BoardAllRoute
  BoardIndexRoute: typeof BoardIndexRoute
}

const BoardRouteChildren: BoardRouteChildren = {
  BoardFolderRoute: BoardFolderRoute,
  BoardAllRoute: BoardAllRoute,
  BoardIndexRoute: BoardIndexRoute,
}

const BoardRouteWithChildren = BoardRoute._addFileChildren(BoardRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoardRoute: BoardRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
